# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-26 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('passwd', models.TextField()),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
