# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CousineBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cousine_name', models.CharField(max_length=50)),
                ('cousine_price', models.CharField(max_length=25)),
                ('service_time', models.CharField(choices=[('B', 'Breakfase'), ('L', 'Lunch'), ('D', 'Dinner'), ('A', 'All day')], max_length=25)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='GroupBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_addr', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='OrderBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TimeField()),
                ('expected_time', models.CharField(choices=[('B', 'Breakfase'), ('L', 'Lunch'), ('D', 'Dinner'), ('A', 'All day')], max_length=25)),
                ('order_state', models.CharField(choices=[('SUB', 'Submitted'), ('CAC', 'Canceled'), ('CF', 'Confirmed'), ('FR', 'Food Ready'), ('FS', 'Finished')], max_length=25)),
                ('cousine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lunch.CousineBase')),
                ('order_by_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lunch.GroupBase')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='RestaurantBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='StaffBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work_phone', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=50)),
                ('email_addr', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='orderbase',
            name='order_by_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lunch.StaffBase'),
        ),
        migrations.AddField(
            model_name='groupbase',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_manager', to='Lunch.StaffBase'),
        ),
        migrations.AddField(
            model_name='groupbase',
            name='members',
            field=models.ManyToManyField(related_name='group_members_list', to='Lunch.StaffBase'),
        ),
        migrations.AddField(
            model_name='cousinebase',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lunch.RestaurantBase'),
        ),
    ]
