# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousinebase',
            name='service_time',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('A', 'All day')], max_length=25),
        ),
    ]
