# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch', '0002_auto_20161003_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousinebase',
            name='service_time',
            field=models.CharField(max_length=25),
        ),
    ]
