# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lunch', '0003_auto_20161003_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousinebase',
            name='restaurant_name',
            field=models.CharField(max_length=50),
        ),
    ]
