# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-05 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('Lunch', '0004_auto_20161003_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('order_serial_no', models.CharField(max_length=25)),
                ('expected_time', models.CharField(choices=[(b'B', b'Breakfase'), (b'L', b'Lunch'), (b'D', b'Dinner'), (b'A', b'All day')], max_length=25)),
                ('order_state', models.CharField(choices=[(b'SUB', b'Submitted'), (b'CAC', b'Canceled'), (b'CF', b'Confirmed'), (b'FR', b'Food Ready'), (b'FS', b'Finished')], max_length=25)),
                ('cousine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lunch.CousineBase')),
                ('order_by_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.UserRecord')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.RemoveField(
            model_name='orderbase',
            name='order_by_group',
        ),
        migrations.AlterField(
            model_name='orderbase',
            name='order_by_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.UserRecord'),
        ),
        migrations.AlterField(
            model_name='orderbase',
            name='order_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
